export const THEME_DEFINITIONS = [
  {
    id: 'bridgemind',
    name: 'BridgeMind',
    category: 'dark',
    style: 'bold',
    description: 'Flagship electric cyan data-streams with indigo precision on void-black.',
    preview: {
      background: '#070a13',
      surface: '#111725',
      border: '#1d2a40',
      text: '#d9e7ff',
      accent: '#22d3ee',
      success: '#6366f1',
      warning: '#0ea5e9',
    },
  },
  {
    id: 'void',
    name: 'Void',
    category: 'dark',
    style: 'tech',
    description: 'Absolute obsidian black with electric indigo signal trails.',
    preview: {
      background: '#0a0a0f',
      surface: '#111118',
      border: '#1e1e2a',
      text: '#c8ccd4',
      accent: '#6366f1',
      success: '#4f46e5',
      warning: '#818cf8',
    },
  },
  {
    id: 'ghost',
    name: 'Ghost',
    category: 'dark',
    style: 'tech',
    description: 'Near-invisible dark where spectral teal flickers in the shadows.',
    preview: {
      background: '#0f1114',
      surface: '#151a1f',
      border: '#26313a',
      text: '#d8dee9',
      accent: '#2dd4bf',
      success: '#14b8a6',
      warning: '#7dd3fc',
    },
  },
  {
    id: 'carbon',
    name: 'Carbon',
    category: 'dark',
    style: 'tech',
    description: 'Matte industrial charcoal cut by warm amber circuitry.',
    preview: {
      background: '#121214',
      surface: '#1a1a1d',
      border: '#2c2c31',
      text: '#e8e6df',
      accent: '#f59e0b',
      success: '#fbbf24',
      warning: '#fb923c',
    },
  },
  {
    id: 'hex',
    name: 'Hex',
    category: 'dark',
    style: 'tech',
    description: 'Pure phosphor green command-line intensity on near-black.',
    preview: {
      background: '#09110d',
      surface: '#112017',
      border: '#1f3a2d',
      text: '#dbfce7',
      accent: '#22c55e',
      success: '#16a34a',
      warning: '#84cc16',
    },
  },
  {
    id: 'storm',
    name: 'Storm',
    category: 'dark',
    style: 'tech',
    description: 'Dark slate clouds with high-voltage yellow energy streaks.',
    preview: {
      background: '#11141b',
      surface: '#1a2029',
      border: '#2c3846',
      text: '#e4edf9',
      accent: '#eab308',
      success: '#fde047',
      warning: '#7dd3fc',
    },
  },
  {
    id: 'stealth',
    name: 'Stealth',
    category: 'dark',
    style: 'tech',
    description: 'Tactical gunmetal dark with restrained military green glow.',
    preview: {
      background: '#111816',
      surface: '#1a2320',
      border: '#2f3c38',
      text: '#dce8e3',
      accent: '#4ade80',
      success: '#22c55e',
      warning: '#84cc16',
    },
  },
  {
    id: 'hologram',
    name: 'Hologram',
    category: 'dark',
    style: 'tech',
    description: 'Ultra-dark base with holographic cyan projection.',
    preview: {
      background: '#081323',
      surface: '#0f2036',
      border: '#1f3757',
      text: '#cfe5ff',
      accent: '#22d3ee',
      success: '#0ea5e9',
      warning: '#a78bfa',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    category: 'dark',
    style: 'tech',
    description: 'Revamped classic with rich navy base and iconic magenta-violet.',
    preview: {
      background: '#1a1b2e',
      surface: '#23253a',
      border: '#3a3e5b',
      text: '#efeaff',
      accent: '#ff79c6',
      success: '#bd93f9',
      warning: '#c084fc',
    },
  },
  {
    id: 'plasma',
    name: 'Plasma',
    category: 'dark',
    style: 'bold',
    description: 'Deep violet-black ionized with hot magenta plasma arcs.',
    preview: {
      background: '#160021',
      surface: '#230032',
      border: '#3a0750',
      text: '#f3d8ff',
      accent: '#d946ef',
      success: '#a855f7',
      warning: '#22d3ee',
    },
  },
  {
    id: 'neon-tokyo',
    name: 'Neon Tokyo',
    category: 'dark',
    style: 'bold',
    description: 'Cyberpunk neon lanes of pink signage and electric cyan rain.',
    preview: {
      background: '#180021',
      surface: '#250031',
      border: '#420654',
      text: '#f9d8ff',
      accent: '#f72585',
      success: '#06b6d4',
      warning: '#ec4899',
    },
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'dark',
    style: 'bold',
    description: 'Volcanic glass deep purple-black with violet edge highlights.',
    preview: {
      background: '#120a1f',
      surface: '#1c1230',
      border: '#33214f',
      text: '#e9ddff',
      accent: '#8b5cf6',
      success: '#a78bfa',
      warning: '#34d399',
    },
  },
  {
    id: 'nebula',
    name: 'Nebula',
    category: 'dark',
    style: 'bold',
    description: 'Deep space void with cosmic purple and stardust glow.',
    preview: {
      background: '#110822',
      surface: '#1b0f32',
      border: '#321a56',
      text: '#eee3ff',
      accent: '#a855f7',
      success: '#c084fc',
      warning: '#818cf8',
    },
  },
  {
    id: 'infrared',
    name: 'Infrared',
    category: 'dark',
    style: 'bold',
    description: 'Thermal imaging at night with orange-crimson signatures.',
    preview: {
      background: '#1f0904',
      surface: '#2f1008',
      border: '#4f1d14',
      text: '#ffe5d9',
      accent: '#f97316',
      success: '#ef4444',
      warning: '#fb923c',
    },
  },
  {
    id: 'nova',
    name: 'Nova',
    category: 'dark',
    style: 'bold',
    description: 'Supernova orange bursts from a deep-violet stellar core.',
    preview: {
      background: '#140b22',
      surface: '#1f1234',
      border: '#352053',
      text: '#f0e5ff',
      accent: '#fb923c',
      success: '#f59e0b',
      warning: '#818cf8',
    },
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    category: 'dark',
    style: 'bold',
    description: 'Outrun retro-futurism in neon pink and sunset orange.',
    preview: {
      background: '#190a24',
      surface: '#271034',
      border: '#40215c',
      text: '#f4dfff',
      accent: '#ec4899',
      success: '#f472b6',
      warning: '#fb923c',
    },
  },
  {
    id: 'cybernetics',
    name: 'Cybernetics',
    category: 'dark',
    style: 'tech',
    description: 'Bio-mechanical dark alloy with surgical green illumination.',
    preview: {
      background: '#111817',
      surface: '#1a2522',
      border: '#2c3b37',
      text: '#d9eee8',
      accent: '#14b8a6',
      success: '#22c55e',
      warning: '#10b981',
    },
  },
  {
    id: 'quantum',
    name: 'Quantum',
    category: 'dark',
    style: 'tech',
    description: 'Supercooled deep blue precision with subatomic cyan.',
    preview: {
      background: '#0a0f1f',
      surface: '#10182d',
      border: '#1f2e4b',
      text: '#d9e8ff',
      accent: '#0ea5e9',
      success: '#38bdf8',
      warning: '#3b82f6',
    },
  },
  {
    id: 'mecha',
    name: 'Mecha',
    category: 'dark',
    style: 'tech',
    description: 'Heavy industrial alloy with reinforced amber heat lines.',
    preview: {
      background: '#15181d',
      surface: '#222730',
      border: '#353c48',
      text: '#e7edf6',
      accent: '#f59e0b',
      success: '#fb923c',
      warning: '#f97316',
    },
  },
  {
    id: 'abyss',
    name: 'Abyss',
    category: 'dark',
    style: 'bold',
    description: 'Midnight ocean trench with bioluminescent teal and magenta.',
    preview: {
      background: '#031019',
      surface: '#081c2a',
      border: '#123140',
      text: '#dbf1ff',
      accent: '#14b8a6',
      success: '#22d3ee',
      warning: '#d946ef',
    },
  },
  {
    id: 'paper',
    name: 'Paper',
    category: 'light',
    style: 'professional',
    description: 'Pure minimal monochrome with clean blue utility accents.',
    preview: {
      background: '#f4f4f5',
      surface: '#ffffff',
      border: '#d4d4d8',
      text: '#222222',
      accent: '#2563eb',
      success: '#334155',
      warning: '#3b82f6',
    },
  },
  {
    id: 'chalk',
    name: 'Chalk',
    category: 'light',
    style: 'professional',
    description: 'Warm cream canvas with calm green-on-parchment contrast.',
    preview: {
      background: '#f8f5ef',
      surface: '#fcfaf5',
      border: '#ddd4c5',
      text: '#2c2a27',
      accent: '#16a34a',
      success: '#22c55e',
      warning: '#2563eb',
    },
  },
  {
    id: 'solar',
    name: 'Solar',
    category: 'light',
    style: 'professional',
    description: 'Solarized warm amber base with precision teal-blue accents.',
    preview: {
      background: '#fdf6e3',
      surface: '#fffaf0',
      border: '#dfd6bc',
      text: '#3e3a31',
      accent: '#0ea5e9',
      success: '#14b8a6',
      warning: '#3b82f6',
    },
  },
  {
    id: 'arctic',
    name: 'Arctic',
    category: 'light',
    style: 'professional',
    description: 'Crisp ice-blue clarity with glacial blue precision lines.',
    preview: {
      background: '#eef4fb',
      surface: '#f7fbff',
      border: '#ccd9ea',
      text: '#1f2937',
      accent: '#2563eb',
      success: '#3b82f6',
      warning: '#0ea5e9',
    },
  },
  {
    id: 'ivory',
    name: 'Ivory',
    category: 'light',
    style: 'professional',
    description: 'Refined ivory workspace with warm amber and steel blue accents.',
    preview: {
      background: '#f8f6f0',
      surface: '#fdfcf9',
      border: '#dad4c7',
      text: '#2f2b24',
      accent: '#b45309',
      success: '#c2410c',
      warning: '#2563eb',
    },
  },
];

export const DEFAULT_THEME_ID = 'void';
export const DEFAULT_DARK_THEME_ID = 'void';
export const DEFAULT_LIGHT_THEME_ID = 'paper';

export const THEME_IDS = THEME_DEFINITIONS.map((theme) => theme.id);
export const DARK_THEME_IDS = THEME_DEFINITIONS.filter((theme) => theme.category === 'dark').map((theme) => theme.id);
export const LIGHT_THEME_IDS = THEME_DEFINITIONS.filter((theme) => theme.category === 'light').map((theme) => theme.id);

export const THEME_MAP = Object.fromEntries(THEME_DEFINITIONS.map((theme) => [theme.id, theme]));

export const isValidTheme = (themeId) => Boolean(THEME_MAP[themeId]);
export const isDarkTheme = (themeId) => DARK_THEME_IDS.includes(themeId);

export const resolveThemeLabel = (theme) => {
  if (!theme) return '';
  return theme.name;
};
